[package]
name = "main"
version = "1.0.0"
authors = ["Diego.Pacheco"]
edition = "2024"

[dependencies]
tokio = { version = "1.36", features = ["full"] } 
diesel = { version = "2.2.7", features = ["postgres"] }
dotenvy = "0.15"