[package]
name = "main-user"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
greet = { version = "0.1.0", path = "../greet" }
