[package]
name = "main"
version = "1.0.0"
authors = ["Diego.Pacheco"]
edition = "2024"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"