[package]
name = "sqlite-manager"
version = "1.1.0"
authors = ["Diego.Pacheco"]
edition = "2024"
rust-version = "1.98.0"

[[bin]]
name = "sqlite-manager"
path = "src/main.rs"

[dependencies]
indicatif = "0.18.6"
rusqlite = { version = "0.40.2", features = ["bundled"] }
rustyline = "18.0.1"

[profile.release]
opt-level = 3
lto = true
strip = true
